export const APP_NAME = 'Krouter'
export const APP_OWNER = 'LightHaru'
export const APP_GITHUB_URL = 'https://github.com/LightHaru'
export const APP_TAGLINE = 'Kiro account routing, quota balancing, and API proxy control from one web dashboard.'
export const APP_TAGLINE_VI = 'Bảng điều khiển web cho tài khoản Kiro, cân bằng quota và Kiro API proxy.'
